version: "3.3"
services:
    mysite:
        build:
            context: ./
        ports:
            - 127.0.0.1:4000:4000
        environment:
            - FLASK_KEY=2138597c1af69610e4e26f1f78134b3d
        volumes: 
            - ./:/home/nonrootuser/codes/
        entrypoint: ["/bin/sh","-c"]
        command:
        - |
            python3 run.py